<?php
namespace App\Http\Controllers;
use App\Models\{Article,Competition,FootballMatch,Team,Player}; use App\Services\{FootballDataService,MatchIntelligenceService};
class WebController extends Controller {
 public function __construct(private FootballDataService $football,private MatchIntelligenceService $intel,private \App\Services\DesignStudioService $design){}
 public function home(){$boot=\Illuminate\Support\Facades\Schema::hasTable('design_profiles')?$this->design->bootstrap('web',app()->getLocale()):['layouts'=>[],'design'=>null];return view('home.index',['live'=>$this->football->live(),'matches'=>$this->football->matchesForDate(),'news'=>Article::latest('published_at')->take(12)->get(),'competitions'=>Competition::where('is_featured',true)->orderBy('sort_order')->get(),'homeBlocks'=>$boot['layouts']['home']??[],'remoteDesign'=>$boot['design']??null]);}
 public function matches(){return view('matches.index',['matches'=>$this->football->matchesForDate(request('date'))]);}
 public function match(FootballMatch $footballMatch){$data=$this->intel->package($footballMatch);$match=$data['match'];$fanMessages=$match->fanMessages()->with('user:id,name,username')->where('status','visible')->limit(30)->get()->reverse();return view('matches.show',array_merge($data,compact('fanMessages')));}
 public function news(){return view('news.index',['articles'=>Article::latest('published_at')->paginate(18)]);} public function article(Article $article){$article->increment('views');return view('news.show',compact('article'));}
 public function team(Team $team){$team->load(['homeMatches'=>fn($q)=>$q->latest('kickoff_at')->limit(10),'awayMatches'=>fn($q)=>$q->latest('kickoff_at')->limit(10)]);$players=Player::where('team_id',$team->id)->orderBy('position')->get();$injuries=\App\Models\PlayerInjury::with('player')->where('team_id',$team->id)->latest()->get();$transfers=\App\Models\Transfer::with(['player','fromTeam','toTeam'])->where(fn($q)=>$q->where('from_team_id',$team->id)->orWhere('to_team_id',$team->id))->latest('transfer_date')->limit(15)->get();return view('teams.show',compact('team','players','injuries','transfers'));}
 public function player(Player $player){$player->load(['team','injuries','seasonStats.competition']);return view('players.show',compact('player'));}
 public function competition(Competition $competition){return view('competitions.show',compact('competition'));}
 public function explore(\Illuminate\Http\Request $request){$q=trim((string)$request->query('q'));$teams=$players=$competitions=$articles=collect();if(mb_strlen($q)>=2){$like='%'.$q.'%';$teams=Team::where(fn($x)=>$x->where('name_ar','like',$like)->orWhere('name_en','like',$like))->limit(12)->get();$players=Player::where('name','like',$like)->limit(12)->get();$competitions=Competition::where(fn($x)=>$x->where('name_ar','like',$like)->orWhere('name_en','like',$like))->limit(12)->get();$articles=Article::whereNotNull('published_at')->where('title','like',$like)->limit(12)->get();}return view('explore',compact('q','teams','players','competitions','articles'));}
 public function sitemap(){ $urls=collect([url('/'),url('/matches'),url('/news'),url('/transfers'),url('/leaderboard')])->merge(Article::whereNotNull('published_at')->latest('published_at')->limit(500)->get()->map(fn($a)=>route('news.show',$a->slug)))->merge(Team::limit(300)->get()->map(fn($t)=>route('team.show',$t->slug)))->merge(Player::limit(500)->get()->map(fn($p)=>route('player.show',$p->slug)));$xml=view('sitemap',compact('urls'))->render();return response($xml,200,['Content-Type'=>'application/xml']);}
 public function transfers(){return view('transfers',['transfers'=>\App\Models\Transfer::with(['player','fromTeam','toTeam'])->latest('transfer_date')->paginate(30)]);} public function leaderboard(){return view('leaderboard',['leaders'=>\App\Models\Prediction::selectRaw('user_id,SUM(points) total_points')->with('user')->groupBy('user_id')->orderByDesc('total_points')->limit(100)->get()]);}
}