@extends('layouts.app')
@section('title','No-Code Experience Studio')
@section('content')
<div class="admin-head"><div><div class="eyebrow">SCORETIME CONTROL ROOM · EXPERIENCE</div><h1>No‑Code Experience Studio</h1><p class="muted">صمّم الصفحات، القوائم، الحملات، المواسم البصرية ونسخ العلامة بدون تعديل PHP أو Flutter.</p></div><div class="row-gap"><a class="btn ghost" href="{{route('admin.design-studio.index')}}">Design Studio</a><a class="btn ghost" href="{{route('admin.dashboard')}}">Dashboard</a></div></div>
@if(session('ok'))<div class="alert success">{{session('ok')}}</div>@endif
<div class="studio-tabs" data-studio-tabs>
 <button class="active" data-tab="pages">Pages</button><button data-tab="schedule">Scheduler</button><button data-tab="experiments">A/B</button><button data-tab="menu">Menus</button><button data-tab="campaigns">Notifications</button><button data-tab="white-label">White‑Label</button>
</div>

<section class="studio-pane active" data-pane="pages">
 <div class="builder-grid">
  <div class="panel"><div class="section-head"><div><span class="eyebrow">DRAG & DROP</span><h2>Custom Page Builder</h2></div><button type="button" class="btn ghost" data-add-block>Add block</button></div>
   <form method="post" action="{{route('admin.no-code-studio.page')}}" id="page-builder-form">@csrf
    <input type="hidden" name="id" id="page-id"><div class="form-grid"><label>Slug<input name="slug" id="page-slug" required placeholder="world-cup-center"></label><label>Surface<select name="surface"><option value="both">Web + App</option><option value="web">Web only</option><option value="app">App only</option></select></label><label>العنوان العربي<input name="title_ar" required></label><label>English title<input name="title_en" required></label><label class="span2">SEO title<input name="seo_title" maxlength="160"></label><label class="span2">SEO description<input name="seo_description" maxlength="260"></label></div>
    <div class="device-switcher"><button type="button" data-preview-size="desktop" class="active">Desktop</button><button type="button" data-preview-size="tablet">Tablet</button><button type="button" data-preview-size="mobile">Mobile</button></div>
    <div id="block-builder" class="block-builder"></div>
    <textarea name="blocks_json" id="blocks-json" hidden>[]</textarea><label class="switch-row"><input type="checkbox" name="is_published" value="1"><span>Publish now</span></label><button class="btn primary">Save page</button>
   </form>
  </div>
  <aside class="panel"><h2>Live Preview</h2><div id="page-preview-shell" class="preview-shell desktop"><div id="page-preview" class="page-preview"><div class="preview-empty">أضف بلوكات لتظهر المعاينة هنا.</div></div></div><p class="muted">المعاينة لا تنفذ JavaScript أو HTML مخصص. البلوكات من Presets آمنة فقط.</p>
   <h3 class="mt-3">Media Library</h3><div class="media-picker">@foreach($media as $m)<button type="button" class="media-thumb" data-media-url="{{Storage::disk($m->disk)->url($m->path)}}" title="{{$m->alt_text}}"><span>{{str_starts_with($m->mime_type??'','image/')?'IMG':'MEDIA'}}</span><small>{{basename($m->path)}}</small></button>@endforeach</div>
  </aside>
 </div>
 <section class="panel section-gap"><h2>Existing Pages</h2><div class="table-wrap"><table><thead><tr><th>Slug</th><th>Title</th><th>Surface</th><th>Status</th><th>Open</th><th></th></tr></thead><tbody>@forelse($pages as $p)<tr><td><b>{{$p->slug}}</b></td><td>{{$p->title['ar']??$p->title['en']??''}}</td><td>{{$p->surface}}</td><td>{{$p->is_published?'Published':'Draft'}}</td><td>@if($p->is_published&&in_array($p->surface,['web','both']))<a href="{{route('custom-page.show',$p->slug)}}" target="_blank">Preview</a>@endif</td><td><form method="post" action="{{route('admin.no-code-studio.page.destroy',$p)}}">@csrf @method('DELETE')<button class="btn ghost" onclick="return confirm('Delete page?')">Delete</button></form></td></tr>@empty<tr><td colspan="6">No custom pages yet.</td></tr>@endforelse</tbody></table></div></section>
</section>

<section class="studio-pane" data-pane="schedule"><div class="builder-grid"><section class="panel"><span class="eyebrow">SCHEDULED PUBLISHING</span><h2>Design Scheduler</h2><form method="post" action="{{route('admin.no-code-studio.schedule')}}" class="form-grid">@csrf<label>Name<input name="name" required placeholder="Champions League Night"></label><label>Accent color<input name="accent" type="color" value="#55E6A5"></label><label>Starts<input name="starts_at" type="datetime-local" required></label><label>Ends<input name="ends_at" type="datetime-local"></label><label class="span2">Temporary product name<input name="product_name"></label><label class="switch-row span2"><input type="checkbox" name="enabled" value="1" checked><span>Enabled</span></label><button class="btn primary span2">Schedule design</button></form></section><section class="panel"><h2>Upcoming / Active</h2>@forelse($schedules as $s)<div class="mini-card"><b>{{$s->name}}</b><span>{{$s->starts_at}} → {{$s->ends_at??'open'}}</span><small>{{$s->enabled?'Enabled':'Disabled'}}</small></div>@empty<p class="muted">No schedules.</p>@endforelse</section></div></section>

<section class="studio-pane" data-pane="experiments"><div class="builder-grid"><section class="panel"><span class="eyebrow">CONTROLLED EXPERIMENTS</span><h2>A/B Theme & Layout Experiments</h2><form method="post" action="{{route('admin.no-code-studio.experiment')}}" class="form-grid">@csrf<label>Name<input name="name" required></label><label>Key<input name="key" required placeholder="home_hero_v2"></label><label>Surface<select name="surface"><option>both</option><option>web</option><option>app</option></select></label><label>Variant B traffic %<input name="traffic_percent" type="number" min="1" max="99" value="50"></label><label class="span2">Variant A JSON<textarea name="variant_a" rows="5">{"heroPreset":"editorial"}</textarea></label><label class="span2">Variant B JSON<textarea name="variant_b" rows="5">{"heroPreset":"cinematic"}</textarea></label><label>Starts<input name="starts_at" type="datetime-local"></label><label>Ends<input name="ends_at" type="datetime-local"></label><label class="switch-row span2"><input type="checkbox" name="enabled" value="1"><span>Enable experiment</span></label><button class="btn primary span2">Create experiment</button></form></section><section class="panel"><h2>Experiments</h2>@forelse($experiments as $e)<div class="mini-card"><b>{{$e->name}}</b><span>{{$e->surface}} · B {{$e->traffic_percent}}%</span><small>{{$e->enabled?'LIVE':'OFF'}}</small></div>@empty<p class="muted">No experiments.</p>@endforelse</section></div></section>

<section class="studio-pane" data-pane="menu"><div class="builder-grid"><section class="panel"><span class="eyebrow">MULTI LEVEL</span><h2>Menu & App Tabs Builder</h2><form method="post" action="{{route('admin.no-code-studio.menu')}}" class="form-grid">@csrf<label>Surface<select name="surface"><option>web</option><option>app</option></select></label><label>Location<input name="location" value="primary" required></label><label>Key<input name="key" required></label><label>Icon key<input name="icon" placeholder="sports_soccer"></label><label>العربية<input name="label_ar" required></label><label>English<input name="label_en" required></label><label class="span2">Target<input name="target" required placeholder="home / matches / page:world-cup-center"></label><label>Parent<select name="parent_id"><option value="">— root —</option>@foreach($menu as $m)<option value="{{$m->id}}">{{$m->surface}} · {{$m->label['en']??$m->key}}</option>@endforeach</select></label><label>Order<input name="sort_order" type="number" value="10" min="0"></label><label class="switch-row span2"><input type="checkbox" name="enabled" value="1" checked><span>Enabled</span></label><button class="btn primary span2">Add menu item</button></form></section><section class="panel"><h2>Menu Tree</h2>@forelse($menu as $m)<div class="menu-tree-item"><div><b>{{$m->label['en']??$m->key}}</b><small>{{$m->surface}} / {{$m->location}} → {{$m->target}}</small></div><form method="post" action="{{route('admin.no-code-studio.menu.destroy',$m)}}">@csrf @method('DELETE')<button class="btn ghost">Delete</button></form>@foreach($m->children as $c)<div class="menu-child">↳ {{$c->label['en']??$c->key}} <small>→ {{$c->target}}</small></div>@endforeach</div>@empty<p class="muted">No menu nodes yet.</p>@endforelse</section></div></section>

<section class="studio-pane" data-pane="campaigns"><div class="builder-grid"><section class="panel"><span class="eyebrow">CAMPAIGN BUILDER</span><h2>Notification Campaign</h2><form method="post" action="{{route('admin.no-code-studio.campaign')}}" class="form-grid">@csrf<label>Name<input name="name" required></label><label>Audience<select name="audience"><option value="all">All users</option><option value="premium">Premium</option><option value="free">Free</option></select></label><label>العنوان العربي<input name="title_ar" required></label><label>English title<input name="title_en" required></label><label>النص العربي<textarea name="body_ar" required></textarea></label><label>English body<textarea name="body_en" required></textarea></label><label class="span2">Schedule<input type="datetime-local" name="scheduled_at"></label><button class="btn primary span2">Save campaign</button></form></section><section class="panel"><h2>Campaigns</h2>@forelse($campaigns as $c)<div class="mini-card"><b>{{$c->name}}</b><span>{{$c->audience}} · {{$c->status}}</span><small>{{$c->scheduled_at??'Not scheduled'}}</small></div>@empty<p class="muted">No campaigns.</p>@endforelse</section></div></section>

<section class="studio-pane" data-pane="white-label"><div class="builder-grid"><section class="panel"><span class="eyebrow">MULTI BRAND</span><h2>White‑Label Branding</h2><form method="post" action="{{route('admin.no-code-studio.white-label')}}" class="form-grid">@csrf<label>Key<input name="key" required placeholder="partner-one"></label><label>Profile name<input name="name" required></label><label class="span2">Host / Domain<input name="host" placeholder="scores.partner.com"></label><label>Product name<input name="product_name" required></label><label>Logo text<input name="logo_text" maxlength="8" required></label><label>Accent<input name="accent" type="color" value="#55E6A5"></label><label class="switch-row"><input type="checkbox" name="enabled" value="1"><span>Enable</span></label><button class="btn primary span2">Save white‑label profile</button></form></section><section class="panel"><h2>Profiles</h2>@forelse($whiteLabels as $w)<div class="mini-card"><b>{{$w->name}}</b><span>{{$w->host?:'No host bound'}}</span><small>{{$w->enabled?'Enabled':'Disabled'}}</small></div>@empty<p class="muted">No white-label profiles.</p>@endforelse</section></div></section>

<script>window.v09Presets=@json([
 ['type'=>'hero','title'=>'Hero / Banner','config'=>['headline'=>'Big match night','subheadline'=>'Everything you need before kickoff','image'=>'','cta'=>'Open Match Center']],
 ['type'=>'live_matches','title'=>'Live Matches','config'=>['limit'=>6]],['type'=>'latest_news','title'=>'Latest News','config'=>['limit'=>8]],['type'=>'breaking_news','title'=>'Breaking News','config'=>['limit'=>5]],['type'=>'competition_table','title'=>'Competition Table','config'=>['limit'=>10]],['type'=>'transfers','title'=>'Transfers','config'=>['limit'=>6]],['type'=>'ad_slot','title'=>'Ad / Sponsor Slot','config'=>['slot'=>'home_mid']],['type'=>'rich_text','title'=>'Rich Text','config'=>['text'=>'Write a short editorial block here.']]
]);</script><script src="/js/v09-no-code.js" defer></script>
@endsection
