<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(){
 Schema::create('transfers',function(Blueprint $t){$t->id();$t->foreignId('player_id')->constrained()->cascadeOnDelete();$t->foreignId('from_team_id')->nullable()->constrained('teams')->nullOnDelete();$t->foreignId('to_team_id')->nullable()->constrained('teams')->nullOnDelete();$t->date('transfer_date')->index();$t->string('type',30)->default('permanent');$t->decimal('fee',14,2)->nullable();$t->string('currency',3)->default('EUR');$t->string('status',30)->default('confirmed')->index();$t->string('source_url')->nullable();$t->boolean('is_featured')->default(false);$t->timestamps();});
 Schema::create('predictions',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('football_match_id')->constrained('football_matches')->cascadeOnDelete();$t->unsignedTinyInteger('home_score');$t->unsignedTinyInteger('away_score');$t->integer('points')->default(0)->index();$t->timestamp('locked_at')->nullable();$t->timestamps();$t->unique(['user_id','football_match_id']);});
 Schema::create('device_sessions',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('token_hash',64)->unique();$t->string('device_name')->nullable();$t->string('platform',30)->nullable();$t->ipAddress('ip_address')->nullable();$t->text('user_agent')->nullable();$t->timestamp('last_seen_at')->nullable();$t->timestamp('revoked_at')->nullable()->index();$t->timestamps();});
 Schema::create('fan_messages',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('football_match_id')->constrained('football_matches')->cascadeOnDelete();$t->string('body',500);$t->string('status',20)->default('visible')->index();$t->timestamps();$t->index(['football_match_id','created_at']);});
 Schema::table('users',function(Blueprint $t){$t->string('two_factor_secret')->nullable()->after('password');$t->timestamp('two_factor_confirmed_at')->nullable()->after('two_factor_secret');$t->string('avatar_url')->nullable();$t->string('timezone',50)->default('UTC');});
 }
 public function down(){Schema::table('users',function(Blueprint $t){$t->dropColumn(['two_factor_secret','two_factor_confirmed_at','avatar_url','timezone']);});Schema::dropIfExists('fan_messages');Schema::dropIfExists('device_sessions');Schema::dropIfExists('predictions');Schema::dropIfExists('transfers');}
};
