<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('player_season_stats', function(Blueprint $t){$t->id();$t->foreignId('player_id')->constrained()->cascadeOnDelete();$t->foreignId('competition_id')->constrained()->cascadeOnDelete();$t->string('season',20)->index();$t->unsignedInteger('appearances')->default(0);$t->unsignedInteger('starts')->default(0);$t->unsignedInteger('minutes')->default(0);$t->unsignedInteger('goals')->default(0)->index();$t->unsignedInteger('assists')->default(0)->index();$t->unsignedInteger('yellow_cards')->default(0);$t->unsignedInteger('red_cards')->default(0);$t->decimal('rating',4,2)->nullable();$t->decimal('xg',7,2)->nullable();$t->decimal('xa',7,2)->nullable();$t->json('extra')->nullable();$t->timestamps();$t->unique(['player_id','competition_id','season'],'player_comp_season_unique');});
  Schema::create('push_devices', function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('token',512)->unique();$t->string('platform',30)->nullable();$t->string('device_name')->nullable();$t->string('locale',10)->default('en');$t->boolean('enabled')->default(true)->index();$t->timestamp('last_seen_at')->nullable();$t->timestamps();});
  Schema::create('notifications', function(Blueprint $t){$t->uuid('id')->primary();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('type',80)->index();$t->string('title',180);$t->text('body')->nullable();$t->json('data')->nullable();$t->timestamp('read_at')->nullable()->index();$t->timestamps();});
  Schema::create('mini_leagues', function(Blueprint $t){$t->id();$t->foreignId('owner_id')->constrained('users')->cascadeOnDelete();$t->string('name',120);$t->string('join_code',12)->unique();$t->boolean('is_public')->default(false)->index();$t->string('season',20)->nullable();$t->timestamps();});
  Schema::create('mini_league_members', function(Blueprint $t){$t->id();$t->foreignId('mini_league_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->integer('points')->default(0)->index();$t->timestamps();$t->unique(['mini_league_id','user_id']);});
  Schema::create('media_assets', function(Blueprint $t){$t->id();$t->foreignId('uploaded_by')->nullable()->constrained('users')->nullOnDelete();$t->string('disk',30)->default('public');$t->string('path');$t->string('mime_type',100)->nullable();$t->unsignedBigInteger('size')->default(0);$t->string('alt_text',180)->nullable();$t->string('credit',180)->nullable();$t->string('license',120)->nullable();$t->json('meta')->nullable();$t->timestamps();$t->index(['mime_type','created_at']);});
  Schema::create('sponsors', function(Blueprint $t){$t->id();$t->string('name',150);$t->string('logo_url')->nullable();$t->string('website_url')->nullable();$t->boolean('is_active')->default(true)->index();$t->dateTime('starts_at')->nullable();$t->dateTime('ends_at')->nullable();$t->timestamps();});
  Schema::create('ad_slots', function(Blueprint $t){$t->id();$t->string('key',80)->unique();$t->string('name',120);$t->string('placement',80)->index();$t->boolean('is_active')->default(true);$t->json('rules')->nullable();$t->timestamps();});
  Schema::create('ad_campaigns', function(Blueprint $t){$t->id();$t->foreignId('sponsor_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('ad_slot_id')->constrained()->cascadeOnDelete();$t->string('title',150);$t->string('image_url')->nullable();$t->string('target_url')->nullable();$t->unsignedBigInteger('impressions')->default(0);$t->unsignedBigInteger('clicks')->default(0);$t->dateTime('starts_at')->nullable();$t->dateTime('ends_at')->nullable();$t->boolean('is_active')->default(true)->index();$t->timestamps();});
  Schema::create('data_provider_sync_logs', function(Blueprint $t){$t->id();$t->string('provider',80)->index();$t->string('resource',80)->index();$t->string('status',20)->index();$t->unsignedInteger('records')->default(0);$t->unsignedInteger('duration_ms')->default(0);$t->text('message')->nullable();$t->json('meta')->nullable();$t->timestamp('started_at');$t->timestamp('finished_at')->nullable();$t->timestamps();});
  Schema::create('app_settings', function(Blueprint $t){$t->id();$t->string('key',120)->unique();$t->json('value')->nullable();$t->boolean('is_public')->default(false)->index();$t->timestamps();});
  Schema::table('users', function(Blueprint $t){$t->json('two_factor_recovery_codes')->nullable()->after('two_factor_secret');$t->string('plan',20)->default('free')->index();$t->timestamp('premium_until')->nullable();});
 }
 public function down(): void {
  Schema::table('users',fn(Blueprint $t)=>$t->dropColumn(['two_factor_recovery_codes','plan','premium_until']));
  foreach(['app_settings','data_provider_sync_logs','ad_campaigns','ad_slots','sponsors','media_assets','mini_league_members','mini_leagues','notifications','push_devices','player_season_stats'] as $table) Schema::dropIfExists($table);
 }
};