import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../core/design/remote_design.dart';
import '../../../core/network/api_client.dart';

class HomeScreen extends ConsumerStatefulWidget {
  const HomeScreen({super.key});
  @override ConsumerState<HomeScreen> createState()=>_HomeScreenState();
}
class _HomeScreenState extends ConsumerState<HomeScreen>{
  bool loading=true; List<dynamic> matches=[]; List<dynamic> news=[]; String? error;
  @override void initState(){super.initState();_load();}
  Future<void> _load() async {try{final api=ApiClient();final m=await api.getMatches();final n=await api.dio.get('/news');if(!mounted)return;setState((){matches=m;news=List<dynamic>.from(n.data['data']??[]);loading=false;error=null;});}catch(e){if(mounted)setState((){loading=false;error='Unable to refresh football feed';});}}
  @override Widget build(BuildContext context){final rd=ref.watch(remoteDesignProvider).asData?.value??RemoteDesign.fallback();final raw=rd.layouts['home'];final blocks=raw is List?raw:<dynamic>[{'type':'live_header','enabled':true},{'type':'live_matches','enabled':true,'limit':6},{'type':'breaking_news','enabled':true,'limit':5},{'type':'latest_news','enabled':true,'limit':8}];return RefreshIndicator(onRefresh:_load,child:CustomScrollView(slivers:[SliverToBoxAdapter(child:_Header(design:rd)),if(loading)const SliverFillRemaining(child:Center(child:CircularProgressIndicator()))else ...blocks.where((x)=>x is Map&&(x['enabled']??true)==true).map((x)=>_block(context,Map<String,dynamic>.from(x),rd)),if(error!=null)SliverToBoxAdapter(child:Padding(padding:const EdgeInsets.all(16),child:Text(error!,textAlign:TextAlign.center))),const SliverToBoxAdapter(child:SizedBox(height:30))]));}
  Widget _block(BuildContext context,Map<String,dynamic> b,RemoteDesign rd){final type='${b['type']}';final limit=(b['limit'] as num?)?.toInt()??6;switch(type){case'live_header':return SliverToBoxAdapter(child:_Hero(design:rd,live:matches.where((m)=>['live','halftime'].contains('${m['status']}')).length));case'favorite_matches':case'live_matches':final data=type=='live_matches'?matches.where((m)=>['live','halftime'].contains('${m['status']}')).take(limit).toList():matches.take(limit).toList();return _MatchSection(title:type=='live_matches'?'LIVE NOW':'Matches for you',items:data);case'breaking_news':return _NewsSection(title:'Breaking News',items:news.where((n)=>(n['is_breaking']??false)==true).take(limit).toList());case'latest_news':return _NewsSection(title:'Latest News',items:news.take(limit).toList());default:return SliverToBoxAdapter(child:Padding(padding:const EdgeInsets.symmetric(horizontal:16,vertical:8),child:Card(child:Padding(padding:const EdgeInsets.all(16),child:Text(type.replaceAll('_',' ').toUpperCase())))));}}
}
class _Header extends StatelessWidget{final RemoteDesign design;const _Header({required this.design});@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.fromLTRB(16,14,16,8),child:Row(children:[Container(width:38,height:38,decoration:BoxDecoration(color:Theme.of(c).colorScheme.primary,borderRadius:BorderRadius.circular(12)),alignment:Alignment.center,child:Text(design.logoText,style:TextStyle(color:Theme.of(c).colorScheme.onPrimary,fontWeight:FontWeight.w900))),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(design.productName,style:const TextStyle(fontSize:21,fontWeight:FontWeight.w900)),Text(design.tagline,maxLines:1,overflow:TextOverflow.ellipsis,style:Theme.of(c).textTheme.bodySmall)])),IconButton(onPressed:(){},icon:const Icon(Icons.notifications_none))]));}
class _Hero extends StatelessWidget{final RemoteDesign design;final int live;const _Hero({required this.design,required this.live});@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.all(16),child:Container(padding:const EdgeInsets.all(22),decoration:BoxDecoration(borderRadius:BorderRadius.circular(26),gradient:LinearGradient(colors:[Theme.of(c).colorScheme.primaryContainer,Theme.of(c).colorScheme.surface])),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('$live MATCHES LIVE',style:TextStyle(color:Theme.of(c).colorScheme.primary,fontWeight:FontWeight.w900)),const SizedBox(height:8),const Text('Football, without the noise.',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),const SizedBox(height:6),Text(design.tagline)])));}
class _MatchSection extends StatelessWidget{final String title;final List<dynamic> items;const _MatchSection({required this.title,required this.items});@override Widget build(BuildContext c)=>SliverMainAxisGroup(slivers:[SliverToBoxAdapter(child:_Title(title)),if(items.isEmpty)const SliverToBoxAdapter(child:Padding(padding:EdgeInsets.all(16),child:Text('No matches right now.')))else SliverList.builder(itemCount:items.length,itemBuilder:(c,i){final m=Map<String,dynamic>.from(items[i]);final h=m['home_team']??m['homeTeam']??{};final a=m['away_team']??m['awayTeam']??{};return Padding(padding:const EdgeInsets.fromLTRB(16,0,16,10),child:Card(child:Padding(padding:const EdgeInsets.all(16),child:Row(children:[Expanded(child:Text('${h['name_en']??h['name']??'Home'}',style:const TextStyle(fontWeight:FontWeight.w800))),Text('${m['home_score']??0}  –  ${m['away_score']??0}',style:const TextStyle(fontSize:18,fontWeight:FontWeight.w900)),Expanded(child:Text('${a['name_en']??a['name']??'Away'}',textAlign:TextAlign.end,style:const TextStyle(fontWeight:FontWeight.w800)))]))));})]);}
class _NewsSection extends StatelessWidget{final String title;final List<dynamic> items;const _NewsSection({required this.title,required this.items});@override Widget build(BuildContext c)=>SliverMainAxisGroup(slivers:[SliverToBoxAdapter(child:_Title(title)),SliverList.builder(itemCount:items.length,itemBuilder:(c,i){final n=Map<String,dynamic>.from(items[i]);return Padding(padding:const EdgeInsets.fromLTRB(16,0,16,10),child:Card(child:Padding(padding:const EdgeInsets.all(15),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${n['category']??'Football'}',style:TextStyle(color:Theme.of(c).colorScheme.primary,fontWeight:FontWeight.w800)),const SizedBox(height:5),Text('${n['title']??''}',style:const TextStyle(fontSize:16,fontWeight:FontWeight.w900))]))));})]);}
class _Title extends StatelessWidget{final String text;const _Title(this.text);@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.fromLTRB(16,20,16,10),child:Text(text,style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900)));}
