import '../../worldclass/presentation/v07_hub_screen.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:koraone/core/i18n/app_strings.dart';
import 'package:koraone/core/theme/theme_controller.dart';
import 'package:koraone/features/auth/presentation/login_screen.dart';
import 'package:koraone/features/worldclass/presentation/world_class_screen.dart';
import 'package:koraone/features/social/presentation/social_hub_screen.dart';
class SettingsScreen extends ConsumerWidget{const SettingsScreen({super.key});@override Widget build(BuildContext context,WidgetRef ref){final s=ref.watch(themeControllerProvider);final c=ref.read(themeControllerProvider.notifier);final t=AppStrings.of(context);return Scaffold(appBar:AppBar(title:Text(t('settings'))),body:ListView(padding:const EdgeInsets.all(16),children:[ListTile(leading:const Icon(Icons.public),title:const Text('Global V0.7 Hub'),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const V07HubScreen()))),Text(t('account'),style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w900)),Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.person)),title:Text(t('login')),subtitle:Text(t('security')),trailing:const Icon(Icons.chevron_right),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const LoginScreen())))),Card(child:ListTile(leading:const Icon(Icons.public),title:const Text('Football Hub'),subtitle:const Text('Leaders • Notifications • Mini Leagues'),trailing:const Icon(Icons.chevron_right),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const WorldClassScreen())))),Card(child:ListTile(leading:const Icon(Icons.auto_awesome),title:const Text('My Football'),subtitle:const Text('Friends • Achievements • Devices'),trailing:const Icon(Icons.chevron_right),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const SocialHubScreen())))),const SizedBox(height:22),Text(t('theme'),style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w900)),const SizedBox(height:8),SegmentedButton<AppThemeName>(segments:[ButtonSegment(value:AppThemeName.stadium,label:Text(t('stadium')),icon:const Icon(Icons.stadium)),ButtonSegment(value:AppThemeName.midnight,label:Text(t('midnight')),icon:const Icon(Icons.dark_mode)),ButtonSegment(value:AppThemeName.light,label:Text(t('light')),icon:const Icon(Icons.light_mode))],selected:{s.theme},onSelectionChanged:(v)=>c.setTheme(v.first)),const SizedBox(height:20),Text('${t('font')}: ${(s.fontScale*100).round()}%'),Slider(value:s.fontScale,min:.85,max:1.30,divisions:9,onChanged:c.setFont),const SizedBox(height:12),DropdownButtonFormField<String>(value:s.locale,decoration:InputDecoration(labelText:t('language'),border:const OutlineInputBorder()),items:const [DropdownMenuItem(value:'ar',child:Text('العربية')),DropdownMenuItem(value:'en',child:Text('English')),DropdownMenuItem(value:'tr',child:Text('Türkçe')),DropdownMenuItem(value:'fr',child:Text('Français')),DropdownMenuItem(value:'es',child:Text('Español'))],onChanged:(v){if(v!=null)c.setLocale(v);}),const SizedBox(height:22),Card(child:SwitchListTile(value:true,onChanged:(_){},title:Text(t('alerts')),subtitle:const Text('Goals • lineups • red cards • full time')))]));}}
