<!doctype html>
@php($locale=app()->getLocale())
@php($rtl=$locale==='ar')
@php($theme=session('theme',auth()->user()?->theme ?? 'stadium'))
@php($fontScale=session('font_scale',auth()->user()?->font_scale ?? 1.0))
@php($designBoot=\Illuminate\Support\Facades\Schema::hasTable('design_profiles') ? app(\App\Services\DesignStudioService::class)->bootstrap('web',$locale) : ['design'=>null,'navigation'=>[]])
@php($remoteDesign=$designBoot['design']??null)
@php($dt=$remoteDesign['tokens']??[])
@php($db=$remoteDesign['branding']??[])
<html lang="{{$locale}}" dir="{{$rtl?'rtl':'ltr'}}" data-theme="{{$theme}}" data-card-style="{{$dt['cardStyle']??'soft'}}" data-header-style="{{$dt['headerStyle']??'glass'}}" data-density="{{$dt['density']??'comfortable'}}" style="--font-scale:{{$fontScale}};--accent:{{$dt['accent']??'#67f5a8'}};--accent2:{{$dt['accent2']??'#48a7ff'}};--bg:{{$dt['background']??'#061019'}};--panel:{{$dt['surface']??'#0d1b28'}};--panel2:{{$dt['surface2']??'#122434'}};--text:{{$dt['text']??'#eef7f3'}};--muted:{{$dt['muted']??'#8fa8b8'}};--radius:{{(int)($dt['radius']??20)}}px">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{csrf_token()}}"><meta name="color-scheme" content="dark light"><meta name="description" content="@yield('description','Independent global football live scores, news, statistics and fan platform.')"><meta name="theme-color" content="#14d990"><link rel="manifest" href="/manifest.webmanifest"><link rel="canonical" href="{{url()->current()}}"><title>@yield('title',$db['productName']??'ScoreTime')</title><link rel="stylesheet" href="/css/app.css"></head>
<body>
<header class="topbar"><div class="shell navrow"><a class="brand" href="/"><span class="brand-mark">{{$db['logoText']??'11'}}</span><span>{{$db['productName']??'ScoreTime'}} <small>V0.9</small></span></a><nav class="desktop-nav">@forelse(collect($designBoot['navigation']??[])->where('location','primary') as $navItem)<a href="{{$navItem['target']}}">{{$navItem['label']}}</a>@empty<a href="/">{{__('ui.home')}}</a><a href="/matches">{{__('ui.matches')}}</a><a href="/news">{{__('ui.news')}}</a>@endforelse</nav><div class="nav-actions"><div class="lang-menu"><button class="icon-btn" data-popover="languages">{{$locale}}</button><div id="languages" class="popover">@foreach(['ar'=>'العربية','en'=>'English','tr'=>'Türkçe','fr'=>'Français','es'=>'Español'] as $code=>$label)<a href="{{route('locale',$code)}}">{{$label}}</a>@endforeach</div></div><button class="icon-btn" data-popover="appearance">Aa</button><div id="appearance" class="popover appearance-pop"><form method="post" action="{{route('appearance')}}">@csrf<label>{{__('ui.theme')}}<select name="theme"><option value="stadium" @selected($theme==='stadium')>Stadium</option><option value="midnight" @selected($theme==='midnight')>Midnight</option><option value="light" @selected($theme==='light')>Light</option></select></label><label>{{__('ui.font_size')}}<input type="range" name="font_scale" min=".85" max="1.30" step=".05" value="{{$fontScale}}"></label><button class="btn primary">{{__('ui.save')}}</button></form></div>@auth @if(auth()->user()->is_admin)<a class="btn admin" href="{{route('admin.dashboard')}}">{{__('ui.admin')}}</a>@endif<form method="post" action="{{route('logout')}}">@csrf<button class="btn ghost">{{__('ui.logout')}}</button></form>@else<a class="btn primary" href="{{route('login')}}">{{__('ui.login')}}</a>@endauth</div></div></header>
@if(session('ok'))<div class="toast">{{session('ok')}}</div>@endif
<main class="shell page">@yield('content')</main>
<footer class="footer"><div class="shell footer-grid"><div><div class="brand"><span class="brand-mark">{{$db['logoText']??'11'}}</span><span>{{$db['productName']??'ScoreTime'}}</span></div><p>Independent football platform. Original interface and editorial system.</p></div><div><b>Platform</b><a href="/matches">{{__('ui.matches')}}</a><a href="/news">{{__('ui.news')}}</a></div><div><b>Account</b>@guest<a href="{{route('login')}}">{{__('ui.login')}}</a><a href="{{route('register')}}">{{__('ui.register')}}</a>@endguest</div></div></footer>
<script src="/js/app.js" defer></script><script>if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));}</script></body></html>
