@extends('layouts.app')
@section('title',($match->homeTeam->name_en ?? 'Home').' vs '.($match->awayTeam->name_en ?? 'Away').' — ScoreTime')
@section('content')
@php($isAr=app()->getLocale()==='ar')
<section class="hero-stage" style="min-height:auto;margin-bottom:16px"><span class="eyebrow">{{$isAr ? ($match->competition?->name_ar ?? $match->competition?->name_en) : ($match->competition?->name_en ?? $match->competition?->name_ar)}} • {{strtoupper($match->status)}}</span><div class="teams-score" style="margin-top:28px"><div class="team-stack"><div class="team-badge">{{mb_substr($isAr ? ($match->homeTeam?->name_ar ?? 'H') : ($match->homeTeam?->name_en ?? 'H'),0,2)}}</div><h2>{{$isAr ? ($match->homeTeam?->name_ar ?? 'Home') : ($match->homeTeam?->name_en ?? 'Home')}}</h2></div><div><div class="big-score">{{$match->home_score}} : {{$match->away_score}}</div><div class="live-footer"><span>{{$match->minute ?? 0}}'</span><span>•</span><span>{{$match->venue}}</span></div></div><div class="team-stack"><div class="team-badge">{{mb_substr($isAr ? ($match->awayTeam?->name_ar ?? 'A') : ($match->awayTeam?->name_en ?? 'A'),0,2)}}</div><h2>{{$isAr ? ($match->awayTeam?->name_ar ?? 'Away') : ($match->awayTeam?->name_en ?? 'Away')}}</h2></div></div></section>
<div class="grid-2"><section class="panel"><span class="eyebrow">TACTICAL</span><h2>Lineups</h2><div class="pitch-pro"><div class="half-line"></div>@foreach($lineups as $entries)@foreach($entries as $e)@if($e->x!==null && $e->y!==null)<div class="shot-dot" style="left:{{$e->x}}%;top:{{$e->y}}%" title="{{$e->player?->name ?? $e->player_name}}"></div>@endif @endforeach @endforeach</div></section><section class="panel"><span class="eyebrow">INTELLIGENCE</span><h2>Match probability</h2><div class="stat-grid"><div class="stat-card"><b>{{$win_probability['home']}}%</b><span>Home</span></div><div class="stat-card"><b>{{$win_probability['draw']}}%</b><span>Draw</span></div><div class="stat-card"><b>{{$win_probability['away']}}%</b><span>Away</span></div></div><h3>Recent form</h3><p class="muted">Home: @foreach($home_form as $f)<b>{{$f['result']}}</b> @endforeach</p><p class="muted">Away: @foreach($away_form as $f)<b>{{$f['result']}}</b> @endforeach</p></section></div>
<div class="grid-2"><section class="panel"><span class="eyebrow">VISUAL DATA</span><h2>Shot map</h2><div class="pitch-pro">@foreach($shot_map as $shot)@php($x=is_array($shot)?($shot['x']??50):$shot->x)@php($y=is_array($shot)?($shot['y']??50):$shot->y)@php($out=is_array($shot)?($shot['outcome']??''):$shot->outcome)<i class="shot-dot {{$out==='goal'?'goal':''}}" style="left:{{$x}}%;top:{{$y}}%"></i>@endforeach</div></section><section class="panel"><span class="eyebrow">MOMENTUM</span><h2>Match flow</h2><div class="momentum-bars">@forelse($momentum as $point)@php($v=is_array($point)?($point['value']??0):$point->value)<i style="height:{{max(4,min(100,abs($v)))}}%;transform:{{($v<0)?'scaleY(-1)':'none'}}"></i>@empty<p class="muted">Momentum will populate from the live provider.</p>@endforelse</div></section></div>
<section class="panel" style="margin-bottom:14px"><span class="eyebrow">LIVE STORY</span><h2>Timeline</h2>@forelse($match->matchEvents as $event)<div class="list-row"><b>{{$event->minute}}' • {{$event->type}}</b><span>{{$event->player?->name}} {{$event->team?->name_en}}</span></div>@empty<p class="muted">Timeline will populate from the live data provider.</p>@endforelse</section>
<section class="panel"><span class="eyebrow">HISTORY</span><h2>Head to head</h2><div class="table-wrap"><table class="data-table"><tbody>@forelse($h2h as $m)<tr><td>{{$m['home_team']['name_en'] ?? 'Home'}}</td><td><b>{{$m['home_score']}} - {{$m['away_score']}}</b></td><td>{{$m['away_team']['name_en'] ?? 'Away'}}</td></tr>@empty<tr><td>No previous meetings loaded.</td></tr>@endforelse</tbody></table></div></section>
@endsection
