@extends('layouts.app')
@section('title',($match->homeTeam->name_en ?? 'Home').' vs '.($match->awayTeam->name_en ?? 'Away'))
@section('content')
<div class="hero match-hero"><span class="eyebrow">{{$match->competition?->name_en}} • {{$match->status}}</span><h1>{{$match->homeTeam?->name_en}} <strong>{{$match->home_score}} : {{$match->away_score}}</strong> {{$match->awayTeam?->name_en}}</h1><p>{{$match->venue}} • {{$match->minute ?? 0}}' • {{$match->referee}}</p></div>
<div class="grid-2"><section class="panel"><h2>Tactical Lineups</h2><div class="pitch-pro"><div class="half-line"></div>@foreach($lineups as $entries)@foreach($entries as $e)@if($e->x!==null && $e->y!==null)<div class="shot-dot" style="left:{{$e->x}}%;top:{{$e->y}}%" title="{{$e->player?->name ?? $e->player_name}}"></div>@endif @endforeach @endforeach</div></section><section class="panel"><h2>Match Probability</h2><div class="stat-grid"><div class="stat-card"><b>{{$win_probability['home']}}%</b><span>Home</span></div><div class="stat-card"><b>{{$win_probability['draw']}}%</b><span>Draw</span></div><div class="stat-card"><b>{{$win_probability['away']}}%</b><span>Away</span></div></div><h3>Form</h3><p>Home: @foreach($home_form as $f)<b>{{$f['result']}}</b> @endforeach</p><p>Away: @foreach($away_form as $f)<b>{{$f['result']}}</b> @endforeach</p></section></div>
<div class="grid-2"><section class="panel"><h2>Shot Map</h2><div class="pitch-pro">@foreach($shot_map as $shot)@php($x=is_array($shot)?($shot['x']??50):$shot->x)@php($y=is_array($shot)?($shot['y']??50):$shot->y)@php($out=is_array($shot)?($shot['outcome']??''):$shot->outcome)<i class="shot-dot {{$out==='goal'?'goal':''}}" style="left:{{$x}}%;top:{{$y}}%"></i>@endforeach</div></section><section class="panel"><h2>Momentum</h2><div class="momentum-bars">@forelse($momentum as $point)@php($v=is_array($point)?($point['value']??0):$point->value)<i style="height:{{max(4,min(100,abs($v)))}}%;transform:{{($v<0)?'scaleY(-1)':'none'}}"></i>@empty<p>No momentum feed yet.</p>@endforelse</div></section></div>
<section class="panel"><h2>Timeline</h2>@forelse($match->matchEvents as $event)<div class="list-row"><b>{{$event->minute}}' • {{$event->type}}</b><span>{{$event->player?->name}} {{$event->team?->name_en}}</span></div>@empty<p>Timeline will populate from the live data provider.</p>@endforelse</section>
<section class="panel"><h2>Head to Head</h2><div class="table-wrap"><table class="data-table"><tbody>@forelse($h2h as $m)<tr><td>{{$m['home_team']['name_en'] ?? 'Home'}}</td><td><b>{{$m['home_score']}} - {{$m['away_score']}}</b></td><td>{{$m['away_team']['name_en'] ?? 'Away'}}</td></tr>@empty<tr><td>No previous meetings loaded.</td></tr>@endforelse</tbody></table></div></section>
@endsection
