<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use App\Models\{DesignProfile,DesignVersion,NavigationItem,PageLayout};
use App\Services\DesignStudioService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class DesignStudioController extends Controller {
 public function index(){ $design=DesignProfile::where('is_active',true)->latest('id')->firstOrFail(); return view('admin.design-studio.index',['design'=>$design,'webHome'=>PageLayout::firstOrNew(['surface'=>'web','page_key'=>'home','locale'=>'*']), 'appHome'=>PageLayout::firstOrNew(['surface'=>'app','page_key'=>'home','locale'=>'*']),'nav'=>NavigationItem::orderBy('surface')->orderBy('sort_order')->get(),'versions'=>$design->versions()->latest('version')->limit(20)->get()]); }
 public function update(Request $r,DesignStudioService $svc){
  $d=$r->validate(['product_name'=>'required|string|max:60','tagline'=>'nullable|string|max:120','logo_text'=>'required|string|max:8','accent'=>'required|regex:/^#[0-9A-Fa-f]{6}$/','accent2'=>'required|regex:/^#[0-9A-Fa-f]{6}$/','background'=>'required|regex:/^#[0-9A-Fa-f]{6}$/','surface'=>'required|regex:/^#[0-9A-Fa-f]{6}$/','surface2'=>'required|regex:/^#[0-9A-Fa-f]{6}$/','text'=>'required|regex:/^#[0-9A-Fa-f]{6}$/','muted'=>'required|regex:/^#[0-9A-Fa-f]{6}$/','radius'=>'required|integer|min:6|max:36','density'=>'required|in:compact,comfortable,spacious','header_style'=>'required|in:solid,glass,floating','card_style'=>'required|in:flat,soft,bordered,glass','features'=>'array','note'=>'nullable|string|max:255']);
  DB::transaction(function()use($d,$r,$svc){$design=DesignProfile::where('is_active',true)->lockForUpdate()->firstOrFail();$svc->snapshot($design,$r->user()->id,$d['note']??'Design Studio update');$design->update(['tokens'=>['accent'=>$d['accent'],'accent2'=>$d['accent2'],'background'=>$d['background'],'surface'=>$d['surface'],'surface2'=>$d['surface2'],'text'=>$d['text'],'muted'=>$d['muted'],'radius'=>$d['radius'],'density'=>$d['density'],'headerStyle'=>$d['header_style'],'cardStyle'=>$d['card_style'],'fontFamily'=>'system'],'branding'=>array_merge($design->branding??[],['productName'=>$d['product_name'],'tagline'=>$d['tagline']??'','logoText'=>$d['logo_text']]),'features'=>collect(['breakingNews','liveTicker','predictions','fanRoom','transfers','premium','ads','social'])->mapWithKeys(fn($k)=>[$k=>in_array($k,$d['features']??[],true)])->all(),'updated_by'=>$r->user()->id]);});$svc->clear();return back()->with('ok','Design published successfully.');
 }
 public function layout(Request $r,DesignStudioService $svc){$d=$r->validate(['surface'=>'required|in:web,app','page_key'=>'required|alpha_dash|max:80','blocks_json'=>'required|json']);$blocks=json_decode($d['blocks_json'],true,512,JSON_THROW_ON_ERROR);abort_unless(is_array($blocks),422);foreach($blocks as $b){abort_unless(is_array($b)&&isset($b['type']),422);} $layout=PageLayout::firstOrNew(['surface'=>$d['surface'],'page_key'=>$d['page_key'],'locale'=>'*']);$layout->fill(['blocks'=>$blocks,'is_published'=>true,'revision'=>($layout->revision?:0)+1,'updated_by'=>$r->user()->id])->save();$svc->clear();return back()->with('ok','Layout published.');}
 public function navigation(Request $r,DesignStudioService $svc){$d=$r->validate(['items'=>'required|array','items.*.id'=>'required|integer|exists:navigation_items,id','items.*.enabled'=>'nullable|boolean','items.*.sort_order'=>'required|integer|min:0|max:100']);foreach($d['items'] as $x)NavigationItem::whereKey($x['id'])->update(['enabled'=>(bool)($x['enabled']??false),'sort_order'=>$x['sort_order']]);$svc->clear();return back()->with('ok','Navigation updated.');}
 public function rollback(DesignVersion $designVersion,Request $r,DesignStudioService $svc){$design=$designVersion->design_profile_id?DesignProfile::findOrFail($designVersion->design_profile_id):abort(404);abort_unless($design->is_active,422);$svc->snapshot($design,$r->user()->id,'Automatic snapshot before rollback');$snap=$designVersion->snapshot;$design->update(['tokens'=>$snap['tokens']??[],'branding'=>$snap['branding']??[],'features'=>$snap['features']??[],'updated_by'=>$r->user()->id]);$svc->clear();return back()->with('ok','Design rolled back to version '.$designVersion->version.'.');}
}
