<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use App\Models\{CustomPage,DesignExperiment,DesignProfile,DesignSchedule,MediaAsset,MenuNode,NotificationCampaign,WhiteLabelProfile};
use App\Services\NoCodeExperienceService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
class NoCodeStudioController extends Controller {
 public function index(){return view('admin.no-code-studio.index',['pages'=>CustomPage::latest()->get(),'schedules'=>DesignSchedule::latest()->get(),'experiments'=>DesignExperiment::latest()->get(),'campaigns'=>NotificationCampaign::latest()->limit(30)->get(),'whiteLabels'=>WhiteLabelProfile::latest()->get(),'menu'=>MenuNode::with('children')->whereNull('parent_id')->orderBy('surface')->orderBy('location')->orderBy('sort_order')->get(),'media'=>MediaAsset::latest()->limit(40)->get(),'design'=>DesignProfile::where('is_active',true)->latest('id')->firstOrFail()]);}
 public function page(Request $r,NoCodeExperienceService $svc){$d=$r->validate(['id'=>'nullable|integer|exists:custom_pages,id','slug'=>'required|alpha_dash|max:120','title_ar'=>'required|string|max:140','title_en'=>'required|string|max:140','surface'=>'required|in:web,app,both','blocks_json'=>'required|json','seo_title'=>'nullable|string|max:160','seo_description'=>'nullable|string|max:260','is_published'=>'nullable|boolean']);$blocks=json_decode($d['blocks_json'],true,512,JSON_THROW_ON_ERROR);abort_unless(is_array($blocks),422);foreach($blocks as $b)abort_unless(is_array($b)&&isset($b['type'])&&is_string($b['type']),422);CustomPage::updateOrCreate(['id'=>$d['id']??null],['slug'=>$d['slug'],'title'=>['ar'=>$d['title_ar'],'en'=>$d['title_en']],'surface'=>$d['surface'],'blocks'=>$blocks,'seo'=>['title'=>$d['seo_title']??$d['title_en'],'description'=>$d['seo_description']??''],'is_published'=>(bool)($d['is_published']??false),'published_at'=>($d['is_published']??false)?now():null,'updated_by'=>$r->user()->id]);$svc->clear();return back()->with('ok','Custom page saved.');}
 public function destroyPage(CustomPage $customPage,NoCodeExperienceService $svc){$customPage->delete();$svc->clear();return back()->with('ok','Custom page deleted.');}
 public function schedule(Request $r,NoCodeExperienceService $svc){$d=$r->validate(['name'=>'required|string|max:120','starts_at'=>'required|date','ends_at'=>'nullable|date|after:starts_at','accent'=>'nullable|regex:/^#[0-9A-Fa-f]{6}$/','product_name'=>'nullable|string|max:60','enabled'=>'nullable|boolean']);$design=DesignProfile::where('is_active',true)->firstOrFail();DesignSchedule::create(['design_profile_id'=>$design->id,'name'=>$d['name'],'starts_at'=>$d['starts_at'],'ends_at'=>$d['ends_at']??null,'enabled'=>(bool)($d['enabled']??false),'overrides'=>['tokens'=>array_filter(['accent'=>$d['accent']??null]),'branding'=>array_filter(['productName'=>$d['product_name']??null])],'created_by'=>$r->user()->id]);$svc->clear();return back()->with('ok','Design schedule created.');}
 public function experiment(Request $r,NoCodeExperienceService $svc){$d=$r->validate(['name'=>'required|string|max:120','key'=>'required|alpha_dash|max:80|unique:design_experiments,key','surface'=>'required|in:web,app,both','traffic_percent'=>'required|integer|min:1|max:99','variant_a'=>'required|json','variant_b'=>'required|json','enabled'=>'nullable|boolean','starts_at'=>'nullable|date','ends_at'=>'nullable|date|after:starts_at']);DesignExperiment::create(['name'=>$d['name'],'key'=>$d['key'],'surface'=>$d['surface'],'traffic_percent'=>$d['traffic_percent'],'variant_a'=>json_decode($d['variant_a'],true,512,JSON_THROW_ON_ERROR),'variant_b'=>json_decode($d['variant_b'],true,512,JSON_THROW_ON_ERROR),'enabled'=>(bool)($d['enabled']??false),'starts_at'=>$d['starts_at']??null,'ends_at'=>$d['ends_at']??null,'created_by'=>$r->user()->id]);$svc->clear();return back()->with('ok','A/B experiment created.');}
 public function whiteLabel(Request $r,NoCodeExperienceService $svc){$d=$r->validate(['key'=>'required|alpha_dash|max:80','name'=>'required|string|max:120','host'=>'nullable|string|max:190','product_name'=>'required|string|max:60','logo_text'=>'required|string|max:8','accent'=>'required|regex:/^#[0-9A-Fa-f]{6}$/','enabled'=>'nullable|boolean']);WhiteLabelProfile::updateOrCreate(['key'=>$d['key']],['name'=>$d['name'],'host'=>$d['host']??null,'branding'=>['productName'=>$d['product_name'],'logoText'=>$d['logo_text']],'tokens'=>['accent'=>$d['accent']],'features'=>[],'enabled'=>(bool)($d['enabled']??false),'updated_by'=>$r->user()->id]);$svc->clear();return back()->with('ok','White-label profile saved.');}
 public function campaign(Request $r){$d=$r->validate(['name'=>'required|string|max:120','title_ar'=>'required|string|max:180','title_en'=>'required|string|max:180','body_ar'=>'required|string|max:500','body_en'=>'required|string|max:500','audience'=>'required|in:all,premium,free','scheduled_at'=>'nullable|date']);NotificationCampaign::create(['name'=>$d['name'],'title'=>['ar'=>$d['title_ar'],'en'=>$d['title_en']],'body'=>['ar'=>$d['body_ar'],'en'=>$d['body_en']],'audience'=>$d['audience'],'status'=>$d['scheduled_at']?'scheduled':'draft','scheduled_at'=>$d['scheduled_at']??null,'created_by'=>$r->user()->id]);return back()->with('ok','Notification campaign saved.');}
 public function menu(Request $r,NoCodeExperienceService $svc){$d=$r->validate(['surface'=>'required|in:web,app','location'=>'required|string|max:40','parent_id'=>'nullable|integer|exists:menu_nodes,id','key'=>'required|alpha_dash|max:80','label_ar'=>'required|string|max:80','label_en'=>'required|string|max:80','target'=>'required|string|max:255','icon'=>'nullable|string|max:60','sort_order'=>'required|integer|min:0|max:999','enabled'=>'nullable|boolean']);MenuNode::create(['surface'=>$d['surface'],'location'=>$d['location'],'parent_id'=>$d['parent_id']??null,'key'=>$d['key'],'label'=>['ar'=>$d['label_ar'],'en'=>$d['label_en']],'target'=>$d['target'],'icon'=>$d['icon']??null,'sort_order'=>$d['sort_order'],'enabled'=>(bool)($d['enabled']??false)]);$svc->clear();return back()->with('ok','Menu item added.');}
 public function destroyMenu(MenuNode $menuNode,NoCodeExperienceService $svc){$menuNode->delete();$svc->clear();return back()->with('ok','Menu item deleted.');}
}
