<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;use App\Services\TotpService;use Illuminate\Http\Request;use Illuminate\Support\Facades\Crypt;use Illuminate\Support\Facades\Hash;
class TwoFactorController extends Controller {
 public function setup(Request $r,TotpService $totp){$u=$r->user();if(!$u->two_factor_secret){$u->forceFill(['two_factor_secret'=>Crypt::encryptString($totp->generateSecret())])->save();}$secret=Crypt::decryptString($u->two_factor_secret);return view('admin.2fa.setup',['secret'=>$secret,'uri'=>$totp->otpauthUri(config('app.name','ScoreTime'),$u->email,$secret)]);}
 public function confirm(Request $r,TotpService $totp){$data=$r->validate(['code'=>'required|digits:6']);$u=$r->user();$secret=Crypt::decryptString($u->two_factor_secret);abort_unless($totp->verify($secret,$data['code']),422,'Invalid verification code.');$codes=$totp->recoveryCodes();$u->forceFill(['two_factor_confirmed_at'=>now(),'two_factor_recovery_codes'=>collect($codes)->map(fn($c)=>Hash::make($c))->values()->all()])->save();$r->session()->put('admin_2fa_passed',true);return view('admin.2fa.recovery',['codes'=>$codes]);}
 public function challenge(){return view('admin.2fa.challenge');}
 public function verify(Request $r,TotpService $totp){$data=$r->validate(['code'=>'required|string|max:20']);$u=$r->user();$ok=false;if(preg_match('/^\\d{6}$/',$data['code']) && $u->two_factor_secret){$ok=$totp->verify(Crypt::decryptString($u->two_factor_secret),$data['code']);}if(!$ok){$codes=$u->two_factor_recovery_codes??[];foreach($codes as $i=>$hash){if(Hash::check(strtoupper($data['code']),$hash)){$ok=true;unset($codes[$i]);$u->forceFill(['two_factor_recovery_codes'=>array_values($codes)])->save();break;}}}abort_unless($ok,422,'Invalid verification code.');$r->session()->put('admin_2fa_passed',true);return redirect()->route('admin.dashboard');}
 public function disable(Request $r){$r->validate(['password'=>'required|current_password']);$r->user()->forceFill(['two_factor_secret'=>null,'two_factor_recovery_codes'=>null,'two_factor_confirmed_at'=>null])->save();$r->session()->forget('admin_2fa_passed');return back()->with('status','Two-factor authentication disabled.');}
}
