import 'package:dio/dio.dart';import 'api_client.dart';
class FootballRepository{FootballRepository([Dio? dio]):_dio=dio??ApiClient().dio;final Dio _dio;
 Future<List<dynamic>> matches()async=>List<dynamic>.from((await _dio.get('/matches')).data['data']); Future<Map<String,dynamic>> match(int id)async=>Map<String,dynamic>.from((await _dio.get('/matches/$id')).data['data']); Future<Map<String,dynamic>> intelligence(int id)async=>Map<String,dynamic>.from((await _dio.get('/matches/$id/intelligence')).data['data']);
 Future<List<dynamic>> transfers()async=>List<dynamic>.from((await _dio.get('/transfers')).data['data']['data']??[]); Future<List<dynamic>> leaderboard()async=>List<dynamic>.from((await _dio.get('/leaderboard')).data['data']??[]); Future<Map<String,dynamic>> search(String q)async=>Map<String,dynamic>.from((await _dio.get('/search',queryParameters:{'q':q})).data['data']); Future<List<dynamic>> leaders({String metric='goals'})async=>List<dynamic>.from((await _dio.get('/stats/leaders',queryParameters:{'metric':metric})).data);
 Future<List<dynamic>> notifications()async=>List<dynamic>.from((await _dio.get('/notifications')).data['data']??[]); Future<void> readAllNotifications()async=>_dio.post('/notifications/read-all'); Future<List<dynamic>> miniLeagues()async=>List<dynamic>.from((await _dio.get('/mini-leagues')).data); Future<Map<String,dynamic>> createMiniLeague(String name)async=>Map<String,dynamic>.from((await _dio.post('/mini-leagues',data:{'name':name})).data); Future<Map<String,dynamic>> joinMiniLeague(String code)async=>Map<String,dynamic>.from((await _dio.post('/mini-leagues/join',data:{'code':code})).data); Future<Map<String,dynamic>> providerHealth()async=>Map<String,dynamic>.from((await _dio.get('/provider/health')).data); Future<void> predict(int id,int h,int a)async=>_dio.post('/matches/$id/prediction',data:{'home_score':h,'away_score':a});
 Future<Map<String,dynamic>> visualMatch(int id)async=>Map<String,dynamic>.from((await _dio.get('/matches/$id/visual')).data['data']); Future<Map<String,dynamic>> teamHub(int id)async=>Map<String,dynamic>.from((await _dio.get('/teams/$id/hub')).data['data']); Future<Map<String,dynamic>> suggestions(String q)async=>Map<String,dynamic>.from((await _dio.get('/search/suggestions',queryParameters:{'q':q})).data['data']); Future<List<dynamic>> trending()async=>List<dynamic>.from((await _dio.get('/search/trending')).data['data']); Future<Map<String,dynamic>> personalizedFeed()async=>Map<String,dynamic>.from((await _dio.get('/personalized-feed')).data['data']); Future<Map<String,dynamic>> premiumStatus()async=>Map<String,dynamic>.from((await _dio.get('/premium/status')).data['data']); Future<List<dynamic>> challenges()async=>List<dynamic>.from((await _dio.get('/challenges')).data['data']); Future<void> createChallenge(String username,String title)async=>_dio.post('/challenges',data:{'username':username,'title':title}); Future<Map<String,dynamic>> level()async=>Map<String,dynamic>.from((await _dio.get('/level')).data['data']);
 Future<Map<String,dynamic>> realtime(int id,{int after=0})async=>Map<String,dynamic>.from((await _dio.get('/matches/$id/realtime',queryParameters:{'after':after})).data['data']); Future<Map<String,dynamic>> comparePlayers(int a,int b)async=>Map<String,dynamic>.from((await _dio.get('/players/$a/compare/$b')).data['data']); Future<List<dynamic>> heatmap(int matchId,int playerId)async=>List<dynamic>.from((await _dio.get('/matches/$matchId/players/$playerId/heatmap')).data['data']); Future<Map<String,dynamic>> transferIntelligence({String status='all'})async=>Map<String,dynamic>.from((await _dio.get('/transfer-intelligence',queryParameters:{'status':status})).data['data']); Future<List<dynamic>> predictionSeasons()async=>List<dynamic>.from((await _dio.get('/prediction-seasons')).data['data']); Future<List<dynamic>> predictionSeasonLeaderboard(int id)async=>List<dynamic>.from((await _dio.get('/prediction-seasons/$id/leaderboard')).data['data']); Future<List<dynamic>> personalizedNews()async=>List<dynamic>.from((await _dio.get('/personalized-news')).data['data']); Future<void> articleSignal(int id,String event)async=>_dio.post('/news/$id/signal',data:{'event':event}); Future<List<dynamic>> friendActivity()async=>List<dynamic>.from((await _dio.get('/friend-activity')).data['data']);
 Future<Map<String,dynamic>> player(int id)async=>Map<String,dynamic>.from((await _dio.get('/players/$id')).data['data']); Future<List<dynamic>> friends()async=>List<dynamic>.from((await _dio.get('/friends')).data['data']); Future<void> addFriend(String username)async=>_dio.post('/friends',data:{'username':username}); Future<List<dynamic>> achievements()async=>List<dynamic>.from((await _dio.get('/achievements')).data['data']); Future<List<dynamic>> sessions()async=>List<dynamic>.from((await _dio.get('/sessions')).data['data']); Future<void> revokeSession(int id)async=>_dio.delete('/sessions/$id'); Future<void> followTeam(int id)async=>_dio.put('/teams/$id/follow',data:{'news':true,'matches':true,'transfers':true}); Future<void> subscribeMatch(int id)async=>_dio.put('/matches/$id/subscribe',data:{'goal':true,'lineup':true,'red_card':true,'kickoff':true,'full_time':true});
 Future<Map<String,dynamic>> worldSummary()async=>Map<String,dynamic>.from((await _dio.get('/world/summary')).data);
 Future<List<dynamic>> worldCountries()async=>List<dynamic>.from((await _dio.get('/world/countries')).data['data']??[]);
 Future<List<dynamic>> worldCompetitions({String q='',String? country,String? type})async=>List<dynamic>.from((await _dio.get('/world/competitions',queryParameters:{if(q.isNotEmpty)'q':q,if(country!=null)'country':country,if(type!=null)'type':type})).data['data']??[]);
 Future<List<dynamic>> worldTeams({String q='',String? country,String? type})async=>List<dynamic>.from((await _dio.get('/world/teams',queryParameters:{if(q.isNotEmpty)'q':q,if(country!=null)'country':country,if(type!=null)'type':type})).data['data']??[]);
 Future<List<dynamic>> worldPlayers({String q='',int? teamId,String? position,String? nationality})async=>List<dynamic>.from((await _dio.get('/world/players',queryParameters:{if(q.isNotEmpty)'q':q,if(teamId!=null)'team_id':teamId,if(position!=null)'position':position,if(nationality!=null)'nationality':nationality})).data['data']??[]);

}