import 'package:flutter/material.dart';

class AppStrings {
  static const supported = ['en', 'ar', 'fr', 'es', 'de', 'tr'];
  static String Function(String) of(BuildContext context) {
    final lang = Localizations.localeOf(context).languageCode;
    return (key) => _data[lang]?[key] ?? _data['en']![key] ?? key;
  }

  static const _data = <String, Map<String, String>>{
    'en': {'home':'Home','matches':'Matches','news':'News','favorites':'Favorites','more':'More','live':'Live','today':'Today','settings':'Settings','theme':'Theme','font':'Font size','language':'Language','login':'Sign in','register':'Create account','email_user':'Email or username','password':'Password','stadium':'ScoreTime','midnight':'Midnight','light':'Light','alerts':'Alerts','account':'Account','security':'Security','world':'World Football','countries':'Countries','competitions':'Competitions','teams':'Teams','players':'Players','search_world':'Search competitions, clubs and players','explore':'Explore','latest':'Latest','transfers':'Transfers','every_moment':'Every moment counts'},
    'ar': {'home':'الرئيسية','matches':'المباريات','news':'الأخبار','favorites':'المفضلة','more':'المزيد','live':'مباشر','today':'اليوم','settings':'الإعدادات','theme':'الثيم','font':'حجم الخط','language':'اللغة','login':'تسجيل الدخول','register':'إنشاء حساب','email_user':'البريد أو اسم المستخدم','password':'كلمة المرور','stadium':'ScoreTime','midnight':'منتصف الليل','light':'فاتح','alerts':'التنبيهات','account':'الحساب','security':'الأمان','world':'كرة القدم العالمية','countries':'الدول','competitions':'البطولات','teams':'الفرق','players':'اللاعبون','search_world':'ابحث في البطولات والأندية واللاعبين','explore':'استكشف','latest':'الأحدث','transfers':'الانتقالات','every_moment':'كل لحظة تحسب'},
    'fr': {'home':'Accueil','matches':'Matchs','news':'Actualités','favorites':'Favoris','more':'Plus','live':'Direct','today':'Aujourd’hui','settings':'Paramètres','theme':'Thème','font':'Taille du texte','language':'Langue','login':'Connexion','register':'Créer un compte','email_user':'E-mail ou utilisateur','password':'Mot de passe','stadium':'ScoreTime','midnight':'Minuit','light':'Clair','alerts':'Alertes','account':'Compte','security':'Sécurité','world':'Football mondial','countries':'Pays','competitions':'Compétitions','teams':'Équipes','players':'Joueurs','search_world':'Rechercher compétitions, clubs et joueurs','explore':'Explorer','latest':'Dernières','transfers':'Transferts','every_moment':'Chaque instant compte'},
    'es': {'home':'Inicio','matches':'Partidos','news':'Noticias','favorites':'Favoritos','more':'Más','live':'En vivo','today':'Hoy','settings':'Ajustes','theme':'Tema','font':'Tamaño de texto','language':'Idioma','login':'Entrar','register':'Crear cuenta','email_user':'Correo o usuario','password':'Contraseña','stadium':'ScoreTime','midnight':'Medianoche','light':'Claro','alerts':'Alertas','account':'Cuenta','security':'Seguridad','world':'Fútbol mundial','countries':'Países','competitions':'Competiciones','teams':'Equipos','players':'Jugadores','search_world':'Buscar competiciones, clubes y jugadores','explore':'Explorar','latest':'Últimas','transfers':'Fichajes','every_moment':'Cada momento cuenta'},
    'de': {'home':'Start','matches':'Spiele','news':'News','favorites':'Favoriten','more':'Mehr','live':'Live','today':'Heute','settings':'Einstellungen','theme':'Design','font':'Schriftgröße','language':'Sprache','login':'Anmelden','register':'Konto erstellen','email_user':'E-Mail oder Benutzername','password':'Passwort','stadium':'ScoreTime','midnight':'Mitternacht','light':'Hell','alerts':'Benachrichtigungen','account':'Konto','security':'Sicherheit','world':'Weltfußball','countries':'Länder','competitions':'Wettbewerbe','teams':'Teams','players':'Spieler','search_world':'Wettbewerbe, Clubs und Spieler suchen','explore':'Entdecken','latest':'Neueste','transfers':'Transfers','every_moment':'Jeder Moment zählt'},
    'tr': {'home':'Ana Sayfa','matches':'Maçlar','news':'Haberler','favorites':'Favoriler','more':'Daha fazla','live':'Canlı','today':'Bugün','settings':'Ayarlar','theme':'Tema','font':'Yazı boyutu','language':'Dil','login':'Giriş','register':'Hesap oluştur','email_user':'E-posta veya kullanıcı adı','password':'Şifre','stadium':'ScoreTime','midnight':'Gece','light':'Açık','alerts':'Bildirimler','account':'Hesap','security':'Güvenlik','world':'Dünya Futbolu','countries':'Ülkeler','competitions':'Turnuvalar','teams':'Takımlar','players':'Oyuncular','search_world':'Turnuva, kulüp ve oyuncu ara','explore':'Keşfet','latest':'Son','transfers':'Transferler','every_moment':'Her an önemlidir'},
  };
}
