<?php
namespace App\Http\Controllers\Api\V1;
use App\Http\Controllers\Controller; use App\Models\{Achievement,FriendActivity,Friendship,TeamFollow,MatchSubscription,User}; use Illuminate\Http\Request;
class SocialController extends Controller {
 public function friends(Request $r){return response()->json(['data'=>Friendship::with(['requester:id,name,username,avatar_url','addressee:id,name,username,avatar_url'])->where(fn($q)=>$q->where('requester_id',$r->user()->id)->orWhere('addressee_id',$r->user()->id))->latest()->get()]);}
 public function request(Request $r){$d=$r->validate(['username'=>'required|string']);$to=User::where('username',$d['username'])->firstOrFail();abort_if($to->id===$r->user()->id,422,'Cannot add yourself.');$f=Friendship::firstOrCreate(['requester_id'=>$r->user()->id,'addressee_id'=>$to->id],['status'=>'pending']);return response()->json(['data'=>$f],201);}
 public function accept(Request $r,Friendship $friendship){abort_unless($friendship->addressee_id===$r->user()->id,403);$friendship->update(['status'=>'accepted','accepted_at'=>now()]);FriendActivity::create(['user_id'=>$r->user()->id,'type'=>'friendship_accepted','subject_type'=>Friendship::class,'subject_id'=>$friendship->id,'meta'=>['with_user_id'=>$friendship->requester_id]]);FriendActivity::create(['user_id'=>$friendship->requester_id,'type'=>'friendship_accepted','subject_type'=>Friendship::class,'subject_id'=>$friendship->id,'meta'=>['with_user_id'=>$r->user()->id]]);return response()->json(['data'=>$friendship]);}
 public function achievements(Request $r){return response()->json(['data'=>Achievement::where('is_active',true)->get()->map(function($a)use($r){$a->earned=$r->user()->belongsToMany(Achievement::class,'user_achievements')->where('achievements.id',$a->id)->exists();return $a;})]);}
 public function followTeam(Request $r,int $team){$f=TeamFollow::updateOrCreate(['user_id'=>$r->user()->id,'team_id'=>$team],$r->validate(['news'=>'sometimes|boolean','matches'=>'sometimes|boolean','transfers'=>'sometimes|boolean']));FriendActivity::create(['user_id'=>$r->user()->id,'type'=>'team_followed','subject_type'=>'team','subject_id'=>$team]);return response()->json(['data'=>$f]);}
 public function subscribeMatch(Request $r,int $match){$d=$r->validate(['goal'=>'sometimes|boolean','lineup'=>'sometimes|boolean','red_card'=>'sometimes|boolean','kickoff'=>'sometimes|boolean','full_time'=>'sometimes|boolean']);$s=MatchSubscription::updateOrCreate(['user_id'=>$r->user()->id,'football_match_id'=>$match],$d);return response()->json(['data'=>$s]);}
}