<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Api\V1\WorldController;
use App\Http\Controllers\Api\V1\{AuthController,CompetitionController,ExploreController,FanRoomController,FavoriteController,FeedController,MatchController,MiniLeagueController,NewsController,NotificationController,PredictionController,ProviderController,StatsController,TeamController,MatchIntelligenceController,ProfileController,SocialController,SessionController,VisualMatchController,TeamHubController,SearchDiscoveryController,ChallengeController,PersonalizedController,PremiumController,RealtimeController,PlayerVisualController,TransferIntelligenceController,NewsPersonalizationController,PredictionSeasonController,FriendActivityController,DesignController,ExperienceController};
Route::prefix('v1')->middleware('throttle:api')->group(function(){
 Route::get('/world/summary',[WorldController::class,'summary']); Route::get('/world/countries',[WorldController::class,'countries']); Route::get('/world/competitions',[WorldController::class,'competitions']); Route::get('/world/teams',[WorldController::class,'teams']); Route::get('/world/players',[WorldController::class,'players']); Route::get('/world/coaches',[WorldController::class,'coaches']);
 Route::post('/auth/register',[AuthController::class,'register'])->middleware('throttle:6,1'); Route::post('/auth/login',[AuthController::class,'login'])->middleware('throttle:login');
 Route::get('/design/bootstrap',[DesignController::class,'bootstrap'])->middleware('throttle:60,1'); Route::get('/experience/bootstrap',[ExperienceController::class,'bootstrap'])->middleware('throttle:60,1'); Route::get('/pages/{customPage:slug}',[ExperienceController::class,'page']); Route::get('/feed',[FeedController::class,'index']); Route::get('/matches',[MatchController::class,'index']); Route::get('/matches/{footballMatch}',[MatchController::class,'show']); Route::get('/matches/{footballMatch}/intelligence',[MatchIntelligenceController::class,'show']);
 Route::get('/news',[NewsController::class,'index']); Route::get('/news/{article}',[NewsController::class,'show']); Route::get('/teams/{team}',[TeamController::class,'show']); Route::get('/competitions/{competition}',[CompetitionController::class,'show']);
 Route::get('/search',[ExploreController::class,'search']); Route::get('/players',[ExploreController::class,'players']); Route::get('/players/{player}',[ExploreController::class,'player']); Route::get('/transfers',[ExploreController::class,'transfers']); Route::get('/stats/leaders',[StatsController::class,'leaders']); Route::get('/leaderboard',[PredictionController::class,'leaderboard']); Route::get('/matches/{footballMatch}/fan-room',[FanRoomController::class,'index']); Route::get('/provider/health',[ProviderController::class,'health']); Route::get('/matches/{footballMatch}/visual',[VisualMatchController::class,'show']); Route::get('/teams/{team}/hub',[TeamHubController::class,'show']); Route::get('/search/suggestions',[SearchDiscoveryController::class,'suggestions']); Route::get('/search/trending',[SearchDiscoveryController::class,'trending']);
 Route::get('/matches/{footballMatch}/realtime',[RealtimeController::class,'snapshot']); Route::get('/matches/{footballMatch}/stream',[RealtimeController::class,'stream'])->middleware('throttle:30,1'); Route::get('/players/{playerA}/compare/{playerB}',[PlayerVisualController::class,'compare']); Route::get('/matches/{match}/players/{player}/heatmap',[PlayerVisualController::class,'heatmap']); Route::get('/transfer-intelligence',[TransferIntelligenceController::class,'index']); Route::get('/prediction-seasons',[PredictionSeasonController::class,'index']); Route::get('/prediction-seasons/{predictionSeason}/leaderboard',[PredictionSeasonController::class,'leaderboard']); Route::get('/personalized-news',[NewsPersonalizationController::class,'feed']);
 Route::middleware('auth:sanctum')->group(function(){
  Route::post('/news/{article}/signal',[NewsPersonalizationController::class,'signal'])->middleware('throttle:60,1'); Route::get('/friend-activity',[FriendActivityController::class,'index']);
  Route::get('/auth/me',[AuthController::class,'me']); Route::post('/auth/logout',[AuthController::class,'logout']); Route::get('/profile',[ProfileController::class,'show']); Route::put('/profile',[ProfileController::class,'update']); Route::put('/profile/password',[ProfileController::class,'password'])->middleware('throttle:5,1');
  Route::get('/favorites',[FavoriteController::class,'index']); Route::post('/favorites',[FavoriteController::class,'store']); Route::delete('/favorites/{favorite}',[FavoriteController::class,'destroy']);
  Route::post('/matches/{footballMatch}/prediction',[PredictionController::class,'store'])->middleware('throttle:20,1'); Route::post('/matches/{footballMatch}/fan-room',[FanRoomController::class,'store'])->middleware('throttle:12,1'); Route::put('/matches/{match}/subscribe',[SocialController::class,'subscribeMatch']); Route::put('/teams/{team}/follow',[SocialController::class,'followTeam']);
  Route::get('/notifications',[NotificationController::class,'index']); Route::patch('/notifications/{notification}/read',[NotificationController::class,'read']); Route::post('/notifications/read-all',[NotificationController::class,'readAll']); Route::post('/push-devices',[NotificationController::class,'registerDevice']); Route::delete('/push-devices',[NotificationController::class,'unregisterDevice']);
  Route::get('/mini-leagues',[MiniLeagueController::class,'index']); Route::post('/mini-leagues',[MiniLeagueController::class,'store'])->middleware('throttle:10,1'); Route::post('/mini-leagues/join',[MiniLeagueController::class,'join'])->middleware('throttle:15,1'); Route::get('/mini-leagues/{miniLeague}',[MiniLeagueController::class,'show']);
  Route::get('/friends',[SocialController::class,'friends']); Route::post('/friends',[SocialController::class,'request'])->middleware('throttle:10,1'); Route::patch('/friends/{friendship}/accept',[SocialController::class,'accept']); Route::get('/achievements',[SocialController::class,'achievements']); Route::get('/sessions',[SessionController::class,'index']); Route::delete('/sessions/{deviceSession}',[SessionController::class,'destroy']); Route::get('/personalized-feed',[PersonalizedController::class,'feed']); Route::get('/premium/status',[PremiumController::class,'status']); Route::get('/challenges',[ChallengeController::class,'index']); Route::post('/challenges',[ChallengeController::class,'store'])->middleware('throttle:10,1'); Route::patch('/challenges/{challenge}/accept',[ChallengeController::class,'accept']); Route::get('/level',[ChallengeController::class,'level']);
 });
});
Route::get('/v1/tv-guide', [\App\Http\Controllers\Api\V1\ProductPolishController::class, 'tvGuide']);
Route::get('/v1/experience-presets', [\App\Http\Controllers\Api\V1\ProductPolishController::class, 'presets']);
Route::middleware('auth:sanctum')->get('/v1/smart-alerts', [\App\Http\Controllers\Api\V1\ProductPolishController::class, 'alerts']);
Route::middleware('auth:sanctum')->post('/v1/smart-alerts', [\App\Http\Controllers\Api\V1\ProductPolishController::class, 'storeAlert']);


Route::get('/v1/calendar', [\App\Http\Controllers\Api\V1\ReleaseCandidateController::class, 'calendar']);
Route::get('/v1/competitions/{competition}/bracket', [\App\Http\Controllers\Api\V1\ReleaseCandidateController::class, 'bracket']);
Route::get('/v1/team-of-week', [\App\Http\Controllers\Api\V1\ReleaseCandidateController::class, 'teamOfWeek']);
Route::get('/v1/players/{player}/radar', [\App\Http\Controllers\Api\V1\ReleaseCandidateController::class, 'playerRadar']);
Route::get('/v1/matches/{match}/story', [\App\Http\Controllers\Api\V1\ReleaseCandidateController::class, 'matchStory']);
Route::get('/v1/onboarding', [\App\Http\Controllers\Api\V1\ReleaseCandidateController::class, 'onboarding']);
Route::get('/v1/deep-links', [\App\Http\Controllers\Api\V1\ReleaseCandidateController::class, 'deepLinkManifest']);

Route::get('/v1/data-status', \App\Http\Controllers\Api\V1\DataStatusController::class)->middleware('throttle:60,1');
