<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder; use App\Models\{Achievement,FootballMatch,MatchLineupEntry,Player,PlayerInjury};
class V05EliteSeeder extends Seeder {public function run():void {
 foreach([
 ['first_prediction','أول توقع','First Prediction','ابدأ رحلتك بتوقع نتيجة مباراة.','Make your first match prediction.',25,'bronze'],['perfect_score','النتيجة المثالية','Perfect Score','توقع النتيجة الدقيقة.','Predict an exact score.',100,'gold'],['five_streak','سلسلة خمسة','Five Streak','خمسة توقعات ناجحة متتالية.','Five successful predictions in a row.',150,'gold'],['club_loyalist','المشجع الوفي','Club Loyalist','تابع فريقك وفعّل تنبيهاته.','Follow a team and enable alerts.',40,'silver'],['social_captain','كابتن المجتمع','Social Captain','كوّن شبكة أصدقاء داخل المنصة.','Build your football friend network.',80,'silver']
 ] as $a) Achievement::updateOrCreate(['key'=>$a[0]],['name_ar'=>$a[1],'name_en'=>$a[2],'description_ar'=>$a[3],'description_en'=>$a[4],'points'=>$a[5],'tier'=>$a[6],'is_active'=>true]);
 if(config('scoretime.seed_demo_data',false)){$m=FootballMatch::with(['homeTeam','awayTeam'])->first(); if($m){$m->update(['home_xg'=>1.42,'away_xg'=>.93,'referee'=>'Demo Referee','attendance'=>41820,'momentum'=>[['minute'=>15,'home'=>58,'away'=>42],['minute'=>30,'home'=>66,'away'=>34]],'shot_map'=>[['team'=>'home','x'=>78,'y'=>42,'xg'=>.21,'outcome'=>'saved'],['team'=>'away','x'=>82,'y'=>58,'xg'=>.16,'outcome'=>'goal']]]);$players=Player::limit(4)->get();foreach($players as $i=>$player){MatchLineupEntry::updateOrCreate(['football_match_id'=>$m->id,'player_id'=>$player->id],['team_id'=>$player->team_id,'player_name'=>$player->name,'shirt_number'=>$player->number,'position'=>$player->position,'x'=>20+($i*20),'y'=>25+($i%2*45),'is_starting'=>true,'is_captain'=>$i===0,'rating'=>$player->rating]);}if($players->first()) PlayerInjury::firstOrCreate(['player_id'=>$players->first()->id,'type'=>'Muscle fatigue'],['team_id'=>$players->first()->team_id,'status'=>'doubtful','started_at'=>now()->subDays(2)->toDateString(),'expected_return_at'=>now()->addDays(5)->toDateString(),'note'=>'Demo medical status for development data only.']);}}
 }}
