@extends('layouts.app')
@section('title','Visual Design Studio')
@section('content')
<div class="admin-head"><div><div class="eyebrow">ADNAN CONTROL ROOM · V0.8</div><h1>Visual Design Studio</h1><p class="muted">غيّر هوية الموقع والتطبيق وترتيب الأقسام بدون تعديل الكود.</p></div><a class="btn ghost" href="{{route('admin.dashboard')}}">← Dashboard</a></div>
<div class="builder-grid">
 <section class="panel builder-form">
  <h2>Brand & Design Tokens</h2>
  <form method="post" action="{{route('admin.design-studio.update')}}" class="form-grid">@csrf @method('PUT')
   <label>Product name<input name="product_name" maxlength="60" value="{{old('product_name',$design->branding['productName']??'ScoreTime')}}" required></label>
   <label>Logo text<input name="logo_text" maxlength="8" value="{{old('logo_text',$design->branding['logoText']??'11')}}" required></label>
   <label class="span2">Tagline<input name="tagline" maxlength="120" value="{{old('tagline',$design->branding['tagline']??'')}}"></label>
   @foreach(['accent'=>'Accent','accent2'=>'Secondary accent','background'=>'Background','surface'=>'Surface','surface2'=>'Raised surface','text'=>'Text','muted'=>'Muted text'] as $k=>$label)
   <label>{{$label}}<div class="color-control"><input type="color" data-color-sync="{{$k}}" value="{{$design->tokens[$k]??'#000000'}}"><input name="{{$k}}" id="color-{{$k}}" value="{{$design->tokens[$k]??'#000000'}}" pattern="^#[0-9A-Fa-f]{6}$" required></div></label>
   @endforeach
   <label>Corner radius<input type="range" name="radius" min="6" max="36" value="{{$design->tokens['radius']??20}}"><small class="muted">6–36 px</small></label>
   <label>Density<select name="density"><option value="compact" @selected(($design->tokens['density']??'')==='compact')>Compact</option><option value="comfortable" @selected(($design->tokens['density']??'comfortable')==='comfortable')>Comfortable</option><option value="spacious" @selected(($design->tokens['density']??'')==='spacious')>Spacious</option></select></label>
   <label>Header<select name="header_style"><option value="solid" @selected(($design->tokens['headerStyle']??'')==='solid')>Solid</option><option value="glass" @selected(($design->tokens['headerStyle']??'glass')==='glass')>Glass</option><option value="floating" @selected(($design->tokens['headerStyle']??'')==='floating')>Floating</option></select></label>
   <label>Cards<select name="card_style"><option value="flat" @selected(($design->tokens['cardStyle']??'')==='flat')>Flat</option><option value="soft" @selected(($design->tokens['cardStyle']??'soft')==='soft')>Soft</option><option value="bordered" @selected(($design->tokens['cardStyle']??'')==='bordered')>Bordered</option><option value="glass" @selected(($design->tokens['cardStyle']??'')==='glass')>Glass</option></select></label>
   <fieldset class="span2 feature-switches"><legend>Feature switches</legend>@foreach(['breakingNews'=>'Breaking News','liveTicker'=>'Live ticker','predictions'=>'Predictions','fanRoom'=>'Fan Room','transfers'=>'Transfers','premium'=>'Premium','ads'=>'Ads','social'=>'Social'] as $k=>$label)<label class="switch-row"><input type="checkbox" name="features[]" value="{{$k}}" @checked($design->features[$k]??false)><span>{{$label}}</span></label>@endforeach</fieldset>
   <label class="span2">Version note<input name="note" maxlength="255" placeholder="مثال: هوية البطولة الجديدة"></label>
   <button class="btn primary span2">Publish design</button>
  </form>
 </section>
 <aside class="panel"><h2>Live preview</h2><div id="design-preview" class="design-preview"><div class="preview-top"><span class="preview-logo">{{$design->branding['logoText']??'11'}}</span><b>{{$design->branding['productName']??'ScoreTime'}}</b></div><div class="preview-hero"><small>LIVE · 72'</small><h3>Manchester City <strong>2–1</strong> Liverpool</h3><p>{{$design->branding['tagline']??''}}</p><button>Match Center</button></div><div class="preview-cards"><i></i><i></i><i></i></div></div><p class="muted">المعاينة محلية. عند Publish تُستخدم الإعدادات في Web وFlutter عبر API.</p></aside>
</div>
<div class="builder-grid section-gap">
 <section class="panel"><h2>Web Home Layout</h2><p class="muted">يمكنك ترتيب البلوكات أو تعطيلها بتعديل JSON المنضبط. لا يسمح بتنفيذ JavaScript أو PHP.</p><form method="post" action="{{route('admin.design-studio.layout')}}">@csrf @method('PUT')<input type="hidden" name="surface" value="web"><input type="hidden" name="page_key" value="home"><textarea name="blocks_json" rows="18" class="code-area">{{json_encode($webHome->blocks??[],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)}}</textarea><button class="btn primary">Publish Web Layout</button></form></section>
 <section class="panel"><h2>App Home Layout</h2><p class="muted">الـFlutter يقرأ هذا التخطيط عند تشغيله ويستطيع عرض/إخفاء وترتيب مكوّنات الصفحة.</p><form method="post" action="{{route('admin.design-studio.layout')}}">@csrf @method('PUT')<input type="hidden" name="surface" value="app"><input type="hidden" name="page_key" value="home"><textarea name="blocks_json" rows="18" class="code-area">{{json_encode($appHome->blocks??[],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)}}</textarea><button class="btn primary">Publish App Layout</button></form></section>
</div>
<section class="panel section-gap"><h2>Navigation Manager</h2><form method="post" action="{{route('admin.design-studio.navigation')}}">@csrf @method('PUT')<div class="table-wrap"><table><thead><tr><th>Surface</th><th>Location</th><th>Key</th><th>Target</th><th>Order</th><th>Enabled</th></tr></thead><tbody>@foreach($nav as $i=>$item)<tr><td>{{$item->surface}}</td><td>{{$item->location}}</td><td><b>{{$item->key}}</b></td><td>{{$item->target}}</td><td><input type="hidden" name="items[{{$i}}][id]" value="{{$item->id}}"><input name="items[{{$i}}][sort_order]" type="number" min="0" max="100" value="{{$item->sort_order}}"></td><td><input type="hidden" name="items[{{$i}}][enabled]" value="0"><input type="checkbox" name="items[{{$i}}][enabled]" value="1" @checked($item->enabled)></td></tr>@endforeach</tbody></table></div><button class="btn primary">Save navigation</button></form></section>
<section class="panel section-gap"><h2>Version History & Rollback</h2><div class="table-wrap"><table><thead><tr><th>Version</th><th>Note</th><th>Date</th><th></th></tr></thead><tbody>@forelse($versions as $v)<tr><td>v{{$v->version}}</td><td>{{$v->note}}</td><td>{{$v->created_at}}</td><td><form method="post" action="{{route('admin.design-studio.rollback',$v)}}">@csrf<button class="btn ghost" onclick="return confirm('Rollback design?')">Rollback</button></form></td></tr>@empty<tr><td colspan="4">No previous versions yet.</td></tr>@endforelse</tbody></table></div></section>
<script src="/js/design-studio.js" defer></script><script>document.querySelectorAll('[data-color-sync]').forEach(p=>p.addEventListener('input',e=>{const k=e.target.dataset.colorSync;document.getElementById('color-'+k).value=e.target.value;const pv=document.getElementById('design-preview');if(k==='accent')pv.style.setProperty('--pv-accent',e.target.value);if(k==='background')pv.style.setProperty('--pv-bg',e.target.value);if(k==='surface')pv.style.setProperty('--pv-surface',e.target.value)}));</script>
@endsection
