<?php $__env->startSection('content'); ?>
<div class="container py-4"><div class="mb-4"><span class="badge bg-primary mb-2">GLOBAL FOOTBALL</span><h1 class="display-6 fw-bold">World Football Directory</h1><p class="text-muted">Countries, leagues, cups, clubs and national teams synchronized from the configured licensed data provider.</p></div>
<div class="row g-3 mb-4"><?php $__currentLoopData = $counts; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $label=>$value): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="col-6 col-lg-3"><div class="card p-3 h-100"><small class="text-muted text-uppercase"><?php echo e($label); ?></small><div class="fs-2 fw-bold"><?php echo e(number_format($value)); ?></div></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div>
<form class="mb-4"><div class="input-group input-group-lg"><input class="form-control" name="q" value="<?php echo e($q); ?>" placeholder="Search competitions"><button class="btn btn-primary">Search</button></div></form>
<div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h4 mb-0">Competitions</h2><a href="<?php echo e(route('world.players')); ?>" class="btn btn-outline-primary">Browse players</a></div>
<div class="row g-3"><?php $__empty_1 = true; $__currentLoopData = $competitions; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $c): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="col-md-6 col-xl-4"><a class="card p-3 h-100 text-decoration-none text-reset" href="<?php echo e(route('competition.show',['competition'=>$c->slug])); ?>"><div class="d-flex gap-3 align-items-center"><?php if($c->logo_url): ?><img src="<?php echo e($c->logo_url); ?>" alt="" width="52" height="52" style="object-fit:contain"><?php endif; ?><div><div class="fw-bold"><?php echo e($c->name_en); ?></div><div class="small text-muted"><?php echo e($c->country ?? 'International'); ?> • <?php echo e(ucfirst($c->type ?? 'league')); ?></div></div></div></a></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><div class="col-12"><div class="alert alert-info">No synchronized competitions yet. Configure the provider and run Global Football Data sync from the admin panel.</div></div><?php endif; ?></div>
<div class="mt-4"><?php echo e($competitions->links()); ?></div></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\ScoreTime_FullStack_V1.3\backend-laravel\resources\views/world/index.blade.php ENDPATH**/ ?>