<!doctype html>
<?php ($locale=app()->getLocale()); ?>
<?php ($rtl=$locale==='ar'); ?>
<?php ($theme=session('theme',auth()->user()?->theme ?? 'stadium')); ?>
<?php ($fontScale=session('font_scale',auth()->user()?->font_scale ?? 1.0)); ?>
<?php ($designBoot=\Illuminate\Support\Facades\Schema::hasTable('design_profiles') ? app(\App\Services\DesignStudioService::class)->bootstrap('web',$locale) : ['design'=>null,'navigation'=>[]]); ?>
<?php ($remoteDesign=$designBoot['design']??null); ?>
<?php ($dt=$remoteDesign['tokens']??[]); ?>
<?php ($db=$remoteDesign['branding']??[]); ?>
<html lang="<?php echo e($locale); ?>" dir="<?php echo e($rtl?'rtl':'ltr'); ?>" data-theme="<?php echo e($theme); ?>" data-card-style="<?php echo e($dt['cardStyle']??'soft'); ?>" data-header-style="<?php echo e($dt['headerStyle']??'glass'); ?>" data-density="<?php echo e($dt['density']??'comfortable'); ?>" style="--font-scale:<?php echo e($fontScale); ?>;--accent:<?php echo e($dt['accent']??'#67f5a8'); ?>;--accent2:<?php echo e($dt['accent2']??'#48a7ff'); ?>;--bg:<?php echo e($dt['background']??'#061019'); ?>;--panel:<?php echo e($dt['surface']??'#0d1b28'); ?>;--panel2:<?php echo e($dt['surface2']??'#122434'); ?>;--text:<?php echo e($dt['text']??'#eef7f3'); ?>;--muted:<?php echo e($dt['muted']??'#8fa8b8'); ?>;--radius:<?php echo e((int)($dt['radius']??20)); ?>px">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="<?php echo e(csrf_token()); ?>"><meta name="color-scheme" content="dark light"><meta name="description" content="<?php echo $__env->yieldContent('description','Independent global football live scores, news, statistics and fan platform.'); ?>"><meta name="theme-color" content="#14d990"><link rel="manifest" href="/manifest.webmanifest"><link rel="canonical" href="<?php echo e(url()->current()); ?>"><title><?php echo $__env->yieldContent('title',$db['productName']??'ScoreTime'); ?></title><link rel="stylesheet" href="/css/app.css"></head>
<body>
<header class="topbar"><div class="shell navrow"><a class="brand" href="/"><span class="brand-mark"><?php echo e($db['logoText']??'11'); ?></span><span><?php echo e($db['productName']??'ScoreTime'); ?> <small>V0.9</small></span></a><nav class="desktop-nav"><?php $__empty_1 = true; $__currentLoopData = collect($designBoot['navigation']??[])->where('location','primary'); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $navItem): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><a href="<?php echo e($navItem['target']); ?>"><?php echo e($navItem['label']); ?></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><a href="/"><?php echo e(__('ui.home')); ?></a><a href="/matches"><?php echo e(__('ui.matches')); ?></a><a href="/news"><?php echo e(__('ui.news')); ?></a><?php endif; ?></nav><div class="nav-actions"><div class="lang-menu"><button class="icon-btn" data-popover="languages"><?php echo e($locale); ?></button><div id="languages" class="popover"><?php $__currentLoopData = ['ar'=>'العربية','en'=>'English','tr'=>'Türkçe','fr'=>'Français','es'=>'Español']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $code=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><a href="<?php echo e(route('locale',$code)); ?>"><?php echo e($label); ?></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div></div><button class="icon-btn" data-popover="appearance">Aa</button><div id="appearance" class="popover appearance-pop"><form method="post" action="<?php echo e(route('appearance')); ?>"><?php echo csrf_field(); ?><label><?php echo e(__('ui.theme')); ?><select name="theme"><option value="stadium" <?php if($theme==='stadium'): echo 'selected'; endif; ?>>Stadium</option><option value="midnight" <?php if($theme==='midnight'): echo 'selected'; endif; ?>>Midnight</option><option value="light" <?php if($theme==='light'): echo 'selected'; endif; ?>>Light</option></select></label><label><?php echo e(__('ui.font_size')); ?><input type="range" name="font_scale" min=".85" max="1.30" step=".05" value="<?php echo e($fontScale); ?>"></label><button class="btn primary"><?php echo e(__('ui.save')); ?></button></form></div><?php if(auth()->guard()->check()): ?> <?php if(auth()->user()->is_admin): ?><a class="btn admin" href="<?php echo e(route('admin.dashboard')); ?>"><?php echo e(__('ui.admin')); ?></a><?php endif; ?><form method="post" action="<?php echo e(route('logout')); ?>"><?php echo csrf_field(); ?><button class="btn ghost"><?php echo e(__('ui.logout')); ?></button></form><?php else: ?><a class="btn primary" href="<?php echo e(route('login')); ?>"><?php echo e(__('ui.login')); ?></a><?php endif; ?></div></div></header>
<?php if(session('ok')): ?><div class="toast"><?php echo e(session('ok')); ?></div><?php endif; ?>
<main class="shell page"><?php echo $__env->yieldContent('content'); ?></main>
<footer class="footer"><div class="shell footer-grid"><div><div class="brand"><span class="brand-mark"><?php echo e($db['logoText']??'11'); ?></span><span><?php echo e($db['productName']??'ScoreTime'); ?></span></div><p>Independent football platform. Original interface and editorial system.</p></div><div><b>Platform</b><a href="/matches"><?php echo e(__('ui.matches')); ?></a><a href="/news"><?php echo e(__('ui.news')); ?></a></div><div><b>Account</b><?php if(auth()->guard()->guest()): ?><a href="<?php echo e(route('login')); ?>"><?php echo e(__('ui.login')); ?></a><a href="<?php echo e(route('register')); ?>"><?php echo e(__('ui.register')); ?></a><?php endif; ?></div></div></footer>
<script src="/js/app.js" defer></script><script>if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));}</script></body></html>
<?php /**PATH C:\xampp\htdocs\ScoreTime_FullStack_V1.3\backend-laravel\resources\views/layouts/app.blade.php ENDPATH**/ ?>